### ISSUE TITLE
No error sents on native devices

### ISSUE THREAD

**Issue by brospars** [getsentry/sentry-capacitor#102]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
```json
"@angular/core": "~10.0.0",
"@capacitor/android": "^2.4.6",
"@capacitor/core": "2.4.6",
"@capacitor/ios": "^2.4.6",
"@sentry/angular": "^6.16.1",
"@sentry/capacitor": "^0.4.1"
```

### Steps to Reproduce

I use the default setup

```ts
// app.module.ts
Sentry.init(
    {
        dsn: 'https://xxxxxx@xxxxx.ingest.sentry.io/xxxxxx',
        release: 'myapp@0.9',
        dist: '0.9',
        tracesSampleRate: 1.0,
        integrations: [
            new TracingIntegrations.BrowserTracing({
                tracingOrigins: ['localhost'],
            }),
        ]
    },
    // Forward the init method from @sentry/angular
    SentryAngular.init
);


@NgModule({
    declarations: [AppComponent],
    entryComponents: [],
    imports: [
        BrowserModule,
        BrowserAnimationsModule,
        IonicModule.forRoot(),
        AppRoutingModule,
        HttpClientModule,
        IonicStorageModule.forRoot()
    ],
    providers: [
        {provide: ErrorHandler, useValue: SentryAngular.createErrorHandler()},
        {provide: RouteReuseStrategy, useClass: IonicRouteStrategy},
        File,
        FileTransfer,
        InAppBrowser,
        AuthGuardService,
        HTTP,
        FileOpener
    ],
    bootstrap: [AppComponent]
})
export class AppModule {}
```
```ts
// app.component.ts
throwError() {
    throw new Error(`Test Thrown Error`);
}

throwErrorNative() {
  Sentry.nativeCrash();
}
```

### Expected Result

Should throw errors and log it t sentry.io with a click of a button but I'm receiving nothing when using real devices (both android and iOS).

### Actual Result

It works when I run it in the browser using `ionic serve`

It throws this error at startup :

```js
Unhandled Promise rejection: Native Client is not available, can't start on native. ; Zone: <root> ; Task: null ; Value: e: Native Client is not available, can't start on native.
```

**Comment by bruno-garcia** [comment]
No native errors for Android nor iOS?

**Comment by brospars** [comment]
Sorry I wasn't clear is my previous message :
- With `ionic serve` and in the browser **everything works** (errors are logged to sentry.
- When i build for iOS or android I get the following error : 
  `Unhandled Promise rejection: Native Client is not available, can't start on native. ; Zone: <root> ; Task: null ; Value: e: Native Client is not available, can't start on native.`

Could this be related to the fact i'm running Capacitor 2 ?

Here is the full output with `debug: true` : 

```js
Sentry Logger [Log]: Integration installed: InboundFilters
vendor.js:195946 Sentry Logger [Log]: Integration installed: FunctionToString
vendor.js:195946 Sentry Logger [Log]: Integration installed: TryCatch
vendor.js:195946 Sentry Logger [Log]: Integration installed: Breadcrumbs
vendor.js:195946 Sentry Logger [Log]: Global Handler attached: onerror
vendor.js:195946 Sentry Logger [Log]: Global Handler attached: onunhandledrejection
vendor.js:195946 Sentry Logger [Log]: Integration installed: GlobalHandlers
vendor.js:195946 Sentry Logger [Log]: Integration installed: LinkedErrors
vendor.js:195946 Sentry Logger [Log]: Integration installed: Dedupe
vendor.js:195946 Sentry Logger [Log]: Integration installed: UserAgent
vendor.js:195946 Sentry Logger [Log]: Integration installed: RewriteFrames
vendor.js:195946 Sentry Logger [Log]: Integration installed: SdkInfo
vendor.js:195946 Sentry Logger [Log]: Integration installed: EventOrigin
vendor.js:195964 Sentry Logger [Warn]: [Tracing] You need to define `tracingOrigins` in the options. Set an array of urls or patterns to trace.
(anonymous) @ vendor.js:195964
vendor.js:195964 Sentry Logger [Warn]: [Tracing] We added a reasonable default for you: localhost,/^\//
(anonymous) @ vendor.js:195964
vendor.js:195946 Sentry Logger [Log]: [Tracing] Starting pageload transaction on scope
vendor.js:195946 Sentry Logger [Log]: Setting idle transaction on scope. Span ID: a28319fe669da124
vendor.js:195946 Sentry Logger [Log]: [Tracing] starting pageload transaction - /
vendor.js:195946 Sentry Logger [Log]: Starting heartbeat
vendor.js:195946 Sentry Logger [Log]: pinging Heartbeat -> current counter: 0
vendor.js:195946 Sentry Logger [Log]: Integration installed: BrowserTracing
vendor.js:195982 Sentry Logger [Error]: Error while triggering instrumentation handler.
Type: console
Name: callback
Error: SentryError: Native Client is not available, can't start on native.
(anonymous) @ vendor.js:195982
vendor.js:195982 Sentry Logger [Error]: Error while triggering instrumentation handler.
Type: console
Name: callback
Error: SentryError: Native Client is not available, can't start on native.
(anonymous) @ vendor.js:195982
vendor.js:178728 Unhandled Promise rejection: Native Client is not available, can't start on native. ; Zone: <root> ; Task: null ; Value: SentryError: Native Client is not available, can't start on native.
    at new SentryError (vendor.js:178369)
    at Module../node_modules/@sentry/capacitor/dist/esm/wrapper.js (vendor.js:170956)
    at __webpack_require__ (runtime.js:85)
    at Module../node_modules/@sentry/capacitor/dist/esm/integrations/sdkinfo.js (vendor.js:170172)
    at __webpack_require__ (runtime.js:85)
    at Module../node_modules/@sentry/capacitor/dist/esm/integrations/index.js (vendor.js:170151)
    at __webpack_require__ (runtime.js:85)
    at Module../node_modules/@sentry/capacitor/dist/esm/sdk.js (vendor.js:170421)
    at __webpack_require__ (runtime.js:85)
    at Module../node_modules/@sentry/capacitor/dist/esm/index.js (vendor.js:170078) SentryError: Native Client is not available, can't start on native.
    at new SentryError (http://localhost/vendor.js:178369:24)
    at Module../node_modules/@sentry/capacitor/dist/esm/wrapper.js (http://localhost/vendor.js:170956:23)
    at __webpack_require__ (http://localhost/runtime.js:85:30)
    at Module../node_modules/@sentry/capacitor/dist/esm/integrations/sdkinfo.js (http://localhost/vendor.js:170172:66)
    at __webpack_require__ (http://localhost/runtime.js:85:30)
    at Module../node_modules/@sentry/capacitor/dist/esm/integrations/index.js (http://localhost/vendor.js:170151:66)
    at __webpack_require__ (http://localhost/runtime.js:85:30)
    at Module../node_modules/@sentry/capacitor/dist/esm/sdk.js (http://localhost/vendor.js:170421:71)
    at __webpack_require__ (http://localhost/runtime.js:85:30)
    at Module../node_modules/@sentry/capacitor/dist/esm/index.js (http://localhost/vendor.js:170078:62)
(anonymous) @ vendor.js:178728
vendor.js:195982 Sentry Logger [Error]: Error while triggering instrumentation handler.
Type: console
Name: callback
Error: SentryError: Native Client is not available, can't start on native.
(anonymous) @ vendor.js:195982
vendor.js:178728 Ionic Native: deviceready event fired after 565 ms
capacitor-runtime.js:393 native SplashScreen.hide (#65053095)
capacitor-runtime.js:417 result SplashScreen.hide (#65053095)
vendor.js:195982 Sentry Logger [Error]: Error while triggering instrumentation handler.
Type: xhr
Name: callback
Error: SentryError: Native Client is not available, can't start on native.
(anonymous) @ vendor.js:195982
capacitor-runtime.js:393 native SplashScreen.hide (#65053096)
capacitor-runtime.js:417 result SplashScreen.hide (#65053096)
vendor.js:195982 Sentry Logger [Error]: Error while triggering instrumentation handler.
Type: history
Name: callback
Error: SentryError: Native Client is not available, can't start on native.
(anonymous) @ vendor.js:195982
vendor.js:195946 Sentry Logger [Log]: [Tracing] Finishing current transaction with op: pageload
vendor.js:195946 Sentry Logger [Log]: [Tracing] finishing IdleTransaction 2021-12-17T13:41:12.305Z pageload
vendor.js:195946 Sentry Logger [Log]: [Tracing] Adding & adjusting spans using Performance API
vendor.js:195946 Sentry Logger [Log]: [Measurements] Adding TTFB
vendor.js:195946 Sentry Logger [Log]: [Tracing] flushing IdleTransaction
vendor.js:195946 Sentry Logger [Log]: [Measurements] Adding measurements to transaction {
  "connection.rtt": {
    "value": 0
  },
  "connection.downlink": {
    "value": 10
  },
  "ttfb": {
    "value": 0
  },
  "ttfb.requestTime": {
    "value": 0
  }
}
vendor.js:195946 Sentry Logger [Log]: [Tracing] Finishing pageload transaction: /.
vendor.js:195946 Sentry Logger [Log]: [Tracing] Starting navigation transaction on scope
vendor.js:195946 Sentry Logger [Log]: Setting idle transaction on scope. Span ID: b8ec2577220d852b
vendor.js:195946 Sentry Logger [Log]: [Tracing] starting navigation transaction - /
vendor.js:195946 Sentry Logger [Log]: Starting heartbeat
vendor.js:195946 Sentry Logger [Log]: pinging Heartbeat -> current counter: 0
vendor.js:195946 Sentry Logger [Log]: Not capturing exception because it's already been captured.
2vendor.js:195982 Sentry Logger [Error]: SentryError: Event processing pipeline threw an error, original event will not be sent. Details have been sent as a new event.
Reason: SentryError: Native Client is not available, can't start on native.
(anonymous) @ vendor.js:195982
vendor.js:195982 Sentry Logger [Error]: Error while triggering instrumentation handler.
Type: xhr
Name: callback
Error: SentryError: Native Client is not available, can't start on native.
(anonymous) @ vendor.js:195982
vendor.js:195946 Sentry Logger [Log]: [Tracing] pushActivity: 97393dbb078aa929
vendor.js:195946 Sentry Logger [Log]: [Tracing] new activities count 1
vendor.js:195946 Sentry Logger [Log]: [Tracing] pushActivity: b26f173636f26146
vendor.js:195946 Sentry Logger [Log]: [Tracing] new activities count 2
vendor.js:195946 Sentry Logger [Log]: [Tracing] pushActivity: ba0b18ca0980a8bb
vendor.js:195946 Sentry Logger [Log]: [Tracing] new activities count 3
vendor.js:195946 Sentry Logger [Log]: [Tracing] pushActivity: 9c366ba558d79259
vendor.js:195946 Sentry Logger [Log]: [Tracing] new activities count 4
vendor.js:195982 Sentry Logger [Error]: Error while triggering instrumentation handler.
Type: fetch
Name: callback
Error: SentryError: Native Client is not available, can't start on native.
(anonymous) @ vendor.js:195982
vendor.js:195946 Sentry Logger [Log]: [Tracing] popActivity 97393dbb078aa929
vendor.js:195946 Sentry Logger [Log]: [Tracing] new activities count 3
vendor.js:195982 Sentry Logger [Error]: Error while triggering instrumentation handler.
Type: fetch
Name: callback
Error: SentryError: Native Client is not available, can't start on native.
(anonymous) @ vendor.js:195982
vendor.js:195946 Sentry Logger [Log]: [Tracing] popActivity b26f173636f26146
vendor.js:195946 Sentry Logger [Log]: [Tracing] new activities count 2
vendor.js:195982 Sentry Logger [Error]: Error while triggering instrumentation handler.
Type: fetch
Name: callback
Error: SentryError: Native Client is not available, can't start on native.
(anonymous) @ vendor.js:195982
vendor.js:195946 Sentry Logger [Log]: [Tracing] popActivity ba0b18ca0980a8bb
vendor.js:195946 Sentry Logger [Log]: [Tracing] new activities count 1
vendor.js:195982 Sentry Logger [Error]: Error while triggering instrumentation handler.
Type: fetch
Name: callback
Error: SentryError: Native Client is not available, can't start on native.
(anonymous) @ vendor.js:195982
vendor.js:195946 Sentry Logger [Log]: [Tracing] popActivity 9c366ba558d79259
vendor.js:195946 Sentry Logger [Log]: [Tracing] new activities count 0
capacitor-runtime.js:393 native App.addListener (#65053097)
vendor.js:195946 Sentry Logger [Log]: [Tracing] finishing IdleTransaction 2021-12-17T13:41:14.045Z navigation
vendor.js:195946 Sentry Logger [Log]: [Tracing] Adding & adjusting spans using Performance API
vendor.js:195946 Sentry Logger [Log]: [Measurements] Adding FCP
vendor.js:195946 Sentry Logger [Log]: [Tracing] flushing IdleTransaction
vendor.js:195946 Sentry Logger [Log]: [Tracing] Finishing navigation transaction: /.
vendor.js:195946 Sentry Logger [Log]: Not capturing exception because it's already been captured.
vendor.js:195982 Sentry Logger [Error]: SentryError: Event processing pipeline threw an error, original event will not be sent. Details have been sent as a new event.
Reason: SentryError: Native Client is not available, can't start on native.
(anonymous) @ vendor.js:195982
```

**Comment by brospars** [comment]
For now I removed `@sentry/capacitor` and use only `@sentry/angular`. It works like a charm :+1:

Since most of our errors comes from JavaScript anyway it doesn't matter to much.

**Comment by jennmueng** [comment]
@brospars When you re-build for iOS and Android can you make sure that the plugin is correctly installed? This looks to me like the plugin is just missing on the native side

**Comment by brospars** [comment]
Yes I did, maybe I missed a step but I don't think so because on iOS when I sync using `ionic capacitor sync ios` it says `Updating iOS native dependencies, etc.`
I think it could be that I'm running Capacitor 2 and not 3. I'll try on a fresh install and come back to you.

**Comment by jennmueng** [comment]
@brospars any updates?

**Comment by bruno-garcia** [comment]
Closing due to inactivity. Feel free to reopen if the issue persists.

**Comment by piotr-cz** [comment]
Same here,
In console a `SentryCapacitor.crash` entry pops up but isn't available at sentry.io - neither when testing on real device nor on android emulator.

**Comment by lucas-zimerman** [comment]
Thanks for the fix :D
