### ISSUE TITLE
Sentry mismatch stacktrace and sourcempas pointing to wrong source code

### ISSUE THREAD

**Issue by StErMi** [getsentry/sentry-capacitor#104]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?

```
"@sentry/capacitor": "^0.4.1",
"@sentry/react": "^6.16.1",
"@sentry/tracing": "^6.16.1",
```

### Steps to Reproduce

We have developed a hybrid mobile application with capacitor + react built with `vite`. We have a sentry + capacitor integration that is not working as expected.

Issues are raised but they are linked to the wrong source file. 

This is the exception on Sentry

```
Error: Test Captured Exception 10
  at onClick(../../src/pages/lists/components/Favorites.tsx:111:28)
  at Rb(../../node_modules/react-dom/cjs/react-dom.production.min.js:105:489)
  at Xb(../../node_modules/react-dom/cjs/react-dom.production.min.js:106:139)
  at Yb(../../node_modules/react-dom/cjs/react-dom.production.min.js:106:200)
  at Ze(../../node_modules/react-dom/cjs/react-dom.production.min.js:149:108)
  at se(../../node_modules/react-dom/cjs/react-dom.production.min.js:150:18)
  at ? (../../node_modules/react-dom/cjs/react-dom.production.min.js:161:311)
  at Jb(../../node_modules/immer/dist/immer.esm.js:1:17584)
  at Nb(../../node_modules/react-dom/cjs/react-dom.production.min.js:104:58)
  at jd(../../node_modules/react-dom/cjs/react-dom.production.min.js:153:22)
  at yc(../../node_modules/react-dom/cjs/react-dom.production.min.js:125:104)
  at hd(../../node_modules/react-dom/cjs/react-dom.production.min.js:124:55)
  at hd([native code])
  at ? (../../node_modules/scheduler/index.js:4:20)
  at Hb(../../node_modules/immer/dist/immer.esm.js:1:17584)
  at gd(../../node_modules/react-dom/cjs/react-dom.production.min.js:123:281)
  at gd([native code])
  at tt(../../node_modules/@sentry/integrations/node_modules/tslib/tslib.es6.js:1:1)
```

but the exception in reality happens on `src/pages/home/HomePage.tsx`

at this point, I'm thinking that Sentry is mismatching (I don't know if on the sentry-capacitor SDK or on sentry.io website) the exception with the source code uploaded.

1) or the client-side sentry is referencing the wrong stack trace (uploading the trace incorrectly)
2) or the sentry.io can't correctly match the correct stack trace with the source maps uploaded

In our app, we have sentry configured like this

```
import * as Sentry from '@sentry/capacitor';
import * as SentryReact from '@sentry/react';
import {Integrations as TracingIntegrations} from '@sentry/tracing';

import {name, version} from './version.json';

if (import.meta.env.VITE_ENVIRONMENT === 'production' || import.meta.env.VITE_ENVIRONMENT === 'staging') {
  Sentry.init(
    {
      environment: import.meta.env.VITE_ENVIRONMENT,
      release: `${name}@${version}+${import.meta.env.VITE_ENVIRONMENT}`,
      dsn: import.meta.env.VITE_SENTRY_DSN,
      integrations: [new TracingIntegrations.BrowserTracing()],
      dist: version,
      debug: false,
      tracesSampleRate: import.meta.env.VITE_ENVIRONMENT === 'production' ? 0.2 : 1,
      attachStacktrace: true,
      ignoreErrors: ['ResizeObserver loop limit exceeded'],
    },
    SentryReact.init,
  );
} else {
  // console.log('SENTRY DISABLED IN DEVELOPMENT ENVIRONMENT');
}

export {};
```

To build the app we do this: 

`tsc && vite build --mode staging && npx cap sync`

then we upload source maps on sentry with this

`sentry-cli releases --org soplaya -p restaurant-mobile files '${name}@${version}+${env}' upload-sourcemaps ./build --dist ${version}`

`name`, `version` and `env` matches what we have specified in `sentry.ts`

Why does this happen? Can we please have some sentry support to look into this issue?

**Comment by bruno-garcia** [comment]
Could you please send a link to an event so we can look at the release/sourcemaps available?

**Comment by StErMi** [comment]
> Could you please send a link to an event so we can look at the release/source maps available?

sure, can we have an email/dm to send it? I would prefer to not send private information on public GitHub ;)

**Comment by bruno-garcia** [comment]
The link in sentry. Only people with access will be able to open the link

**Comment by lucas-zimerman** [comment]
Closing due to inactivity, please let us know if the problem still exists.
