### ISSUE TITLE
yarn upgrade to 0.11 fails - no such file or directory, open '[...]/node_modules/@sentry/capacitor/scripts../Package.json'

### ISSUE THREAD

**Issue by borgoat** [getsentry/sentry-capacitor#298]
I am trying to upgrade to 0.11, but am getting errors from yarn

### Environment

yarn 3.2.0 with node modules

### Steps to Reproduce

1. Upgrade to `"@sentry/capacitor": "0.11.0"`
2. Run `yarn install`

### Expected Result

Run `yarn install` and get 

### Actual Result

I get an error on `yarn install`:

```
➤ YN0000: ┌ Link step
➤ YN0007: │ @aws-amplify/cli@npm:10.6.2 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.17.4 must be built because it never has been before or the last one failed
➤ YN0007: │ swiper@npm:8.4.6 must be built because it never has been before or the last one failed
➤ YN0008: │ @nrwl/angular@npm:15.5.3 [584e3] must be rebuilt because its dependency tree changed
➤ YN0007: │ @sentry/capacitor@npm:0.11.0 [584e3] must be built because it never has been before or the last one failed
➤ YN0009: │ @sentry/capacitor@npm:0.11.0 [584e3] couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/6p/hmgy9dyd53sdf4db6mgks94h0000gn/T/xfs-8ee69e50/build.log)
➤ YN0008: │ yeekatee@workspace:. must be rebuilt because its dependency tree changed
➤ YN0000: └ Completed in 32s 526ms
➤ YN0000: Failed with errors in 50s 501ms
```

The content of `/private/var/folders/6p/hmgy9dyd53sdf4db6mgks94h0000gn/T/xfs-8ee69e50/build.log`

```
# This file contains the result of Yarn building a package (@sentry/capacitor@virtual:584e3a330b4362c4c2147a0929adf706df23b823ee694a5fee61049f634bd39ff1222a6675c4b1dce7c8575307aa4b5731b5524826f3eb0988140430323e4d3b#npm:0.11.0)
# Script name: postinstall

node:internal/fs/utils:346
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/borgoat/yeekatee/node_modules/@sentry/capacitor/scripts../Package.json'
    at Object.openSync (node:fs:584:3)
    at Object.readFileSync (node:fs:452:35)
    at GetRequiredSiblingVersion (/Users/borgoat/yeekatee/node_modules/@sentry/capacitor/scripts/check-siblings.js:45:35)
    at Object.<anonymous> (/Users/borgoat/yeekatee/node_modules/@sentry/capacitor/scripts/check-siblings.js:113:24)
    at Module._compile (node:internal/modules/cjs/loader:1239:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:935:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:84:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/borgoat/yeekatee/node_modules/@sentry/capacitor/scripts../Package.json'
}

Node.js v19.4.0

```

I guess this is related to #248: https://github.com/getsentry/sentry-capacitor/pull/248#discussion_r1073948447

**Comment by lucas-zimerman** [comment]
Hi and thank you for opening this issue :D 
The problem should be sorted out on the next release!

**Comment by borgoat** [comment]
Hi @lucas-zimerman thanks for the feedback.

I'm afraid I still see the same behaviour in 0.11.1 - although `package.json` appears lowercase - I guess you mean next minor release?

```
# This file contains the result of Yarn building a package (@sentry/capacitor@virtual:584e3a330b4362c4c2147a0929adf706df23b823ee694a5fee61049f634bd39ff1222a6675c4b1dce7c8575307aa4b5731b5524826f3eb0988140430323e4d3b#npm:0.11.1)
# Script name: postinstall

node:internal/fs/utils:346
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/borgoat/Workspace/yeekatee/node_modules/@sentry/capacitor/scripts../package.json'
    at Object.openSync (node:fs:584:3)
    at Object.readFileSync (node:fs:452:35)
    at GetRequiredSiblingVersion (/Users/borgoat/Workspace/yeekatee/node_modules/@sentry/capacitor/scripts/check-siblings.js:45:35)
    at Object.<anonymous> (/Users/borgoat/Workspace/yeekatee/node_modules/@sentry/capacitor/scripts/check-siblings.js:113:24)
    at Module._compile (node:internal/modules/cjs/loader:1239:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:935:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:84:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/borgoat/Workspace/yeekatee/node_modules/@sentry/capacitor/scripts../package.json'
}

Node.js v19.4.0
```

**Comment by lucas-zimerman** [comment]
That's odd, I'll check it...
for the time being, could you run `yarn install --update-sentry-capacitor` ?

**Comment by inpt333** [comment]
Hi @lucas-zimerman , when are you planning to release a new version of the plugin, so we can solve this issue?

**Comment by lucas-zimerman** [comment]
A new release fixing this issue was released
