### ISSUE TITLE
Support frame rewriting for migrated Cordova apps using ionic scheme

### ISSUE THREAD

**Issue by jskrepnek** [getsentry/sentry-capacitor#391]
Apps that migrated from Cordova to Capacitor may still be using `ionic` as the server scheme.  The default integration that [rewrites frames](https://github.com/getsentry/sentry-capacitor/blob/main/src/sdk.ts#L50) does not take this into account, resulting in invalid frame urls .  The only recourse is to apply custom processing before events are sent to fix the filenames.

I think it makes sense to bake support for the `ionic` scheme into the plugin, but an alternative could be to provide a configuration point for the removal of custom schemes and protocols.

**Comment by lucas-zimerman** [comment]
By any chance do you have any sample/example of the affected stacktrace?

**Comment by jskrepnek** [comment]
Hi @lucas-zimerman 

Here's an example:

```
at testWebUnhandledError(app:///ionic://localhost/7214.a1b610e6cad107f9.js:1:42273)
  at Df(app:///ionic://localhost/main.569f5323c6e54cbf.js:1:3193112)
  at be(app:///ionic://localhost/main.569f5323c6e54cbf.js:1:3193288)
  at ? (app:///ionic://localhost/main.569f5323c6e54cbf.js:1:3297173)
  at rt(app:///ionic://localhost/main.569f5323c6e54cbf.js:1:2440127)
  at onInvokeTask(app:///ionic://localhost/main.569f5323c6e54cbf.js:1:3230564)
  at ? (app:///ionic://localhost/polyfills.ced8424825c55a82.js:1:3466)
  at ? (app:///ionic://localhost/polyfills.ced8424825c55a82.js:1:9604)
  at l(app:///ionic://localhost/polyfills.ced8424825c55a82.js:1:23295)
  at c(app:///ionic://localhost/polyfills.ced8424825c55a82.js:1:23678)
```

**Comment by lucas-zimerman** [comment]
Ok, thank you for the sample, I'll add this to the queue of features to be done!

**Comment by jskrepnek** [comment]
Seems like the bot is not working

**Comment by jskrepnek** [comment]
don't close
