### ISSUE TITLE
Breadcrumb deserializer expects object, but envelope contains array

### ISSUE THREAD

**Issue by mlostekk** [getsentry/sentry-capacitor#451]
When sending errors with breadcrumps, the envelope looks like this

```
{
    "event_id": "13817c8e689849d78774f77981a8af1b",
    "sent_at": "2023-08-31T14:26:03.295Z",
    "sdk":
    {
        "name": "sentry.javascript.browser",
        "version": "7.56.0"
    }
}
{
    "type": "event",
    "content_type": "application/json",
    "length": 2868
}
{
    "exception":
    {
        "values":
        [
            {
                "type": "TypeError",
                "value": "Cannot read properties of undefined (reading 'polaroid')",
                "stacktrace":
                {
                    "frames":
                    [
                        {
                            "filename": "app:///webpack-internal:///./node_modules/tslib/tslib.es6.mjs",
                            "function": "fulfilled",
                            "in_app": true,
                            "lineno": 151,
                            "colno": 56
                        },
                        {
                            "filename": "app:///webpack-internal:///./node_modules/tslib/tslib.es6.mjs",
                            "function": "Object.eval [as next]",
                            "in_app": true,
                            "lineno": 161,
                            "colno": 51
                        },
                        {
                            "filename": "app:///webpack-internal:///./node_modules/tslib/tslib.es6.mjs",
                            "function": "step",
                            "in_app": true,
                            "lineno": 180,
                            "colno": 21
                        },
                        {
                            "filename": "app:///webpack-internal:///./src/System/Area/MetaPreloadSystem.ts",
                            "function": "MetaPreloadSystem.eval",
                            "in_app": true,
                            "lineno": 268,
                            "colno": 30
                        },
                        {
                            "filename": "app:///webpack-internal:///./src/System/Area/MetaPreloadSystem.ts",
                            "function": "MetaPreloadSystem.postLoad",
                            "in_app": true,
                            "lineno": 280,
                            "colno": 14
                        },
                        {
                            "filename": "app:///webpack-internal:///./src/System/Area/MetaPreloadSystem.ts",
                            "function": "MetaPreloadSystem.addFutureStoriesOverlaysToLoad",
                            "in_app": true,
                            "lineno": 451,
                            "colno": 94
                        },
                        {
                            "filename": "app:///<anonymous>",
                            "function": "Array.forEach",
                            "in_app": true
                        },
                        {
                            "filename": "app:///webpack-internal:///./src/System/Area/MetaPreloadSystem.ts",
                            "function": "eval",
                            "in_app": true,
                            "lineno": 454,
                            "colno": 13
                        },
                        {
                            "filename": "app:///webpack-internal:///./src/System/Area/MetaPreloadSystem.ts",
                            "function": "addStoriesOverlaysToLoad",
                            "in_app": true,
                            "lineno": 550,
                            "colno": 12
                        },
                        {
                            "filename": "app:///webpack-internal:///./src/System/Area/MetaPreloadSystem.ts",
                            "function": "getStoriesOverlaysToLoad",
                            "in_app": true,
                            "lineno": 562,
                            "colno": 107
                        },
                        {
                            "filename": "app:///<anonymous>",
                            "function": "Array.forEach",
                            "in_app": true
                        },
                        {
                            "filename": "app:///webpack-internal:///./src/System/Area/MetaPreloadSystem.ts",
                            "function": "eval",
                            "in_app": true,
                            "lineno": 563,
                            "colno": 111
                        }
                    ]
                },
                "mechanism":
                {
                    "type": "generic",
                    "handled": true
                }
            }
        ]
    },
    "level": "error",
    "event_id": "13817c8e689849d78774f77981a8af1b",
    "platform": "javascript",
    "timestamp": 1693491963.29,
    "environment": "development",
    "release": "android|0.1.15(15)|1.91.0|230831491",
    "sdk":
    {
        "integrations":
        [
            "InboundFilters",
            "FunctionToString",
            "TryCatch",
            "Breadcrumbs",
            "GlobalHandlers",
            "LinkedErrors",
            "Dedupe",
            "HttpContext",
            "RewriteFrames",
            "SdkInfo",
            "EventOrigin",
            "DeviceContext"
        ],
        "name": "sentry.javascript.capacitor",
        "version": "0.12.2",
        "packages":
        [
            {
                "name": "npm:@sentry/capacitor",
                "version": "0.12.2"
            },
            {
                "name": "npm:@sentry/browser",
                "version": "7.56.0"
            }
        ]
    },
    "extra":
    {
        "level": 2,
        "chapter": 1,
        "area": 1,
        "maxTexture": 4096,
        "glVendor": "ARM",
        "glRenderer": "Mali-G77"
    },
    "tags":
    {
        "category": "None",
        "event.origin": "javascript",
        "event.environment": "javascript"
    },
    "user":
    {
        "id": "soho_user_id"
    },
    "breadcrumbs":
    [],
    "request":
    {
        "url": "http://localhost/",
        "headers":
        {
            "User-Agent": "Mozilla/5.0 (Linux; Android 13; SM-G980F Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36"
        }
    },
    "contexts":
    {}
}

```

But the `SentryBaseEvent` uses the `Breadcrumb.Deserializer` when it hits the breadcrumb section. The deserializer itself starts with a `reader.beginObject();` which is not correct, and this leads to 

```
Sentry                   E  Failed to deserialize object in list.
                            java.lang.IllegalStateException: Expected BEGIN_OBJECT but was END_ARRAY at line 1 column 3468 path $.breadcrumbs[0]
                            	at io.sentry.vendor.gson.stream.JsonReader.beginObject(JsonReader.java:392)
                            	at io.sentry.Breadcrumb$Deserializer.deserialize(Breadcrumb.java:596)
                            	at io.sentry.Breadcrumb$Deserializer.deserialize(Breadcrumb.java:591)
                            	at io.sentry.JsonObjectReader.nextList(JsonObjectReader.java:94)
                            	at io.sentry.SentryBaseEvent$Deserializer.deserializeValue(SentryBaseEvent.java:440)
                            	at io.sentry.SentryEvent$Deserializer.deserialize(SentryEvent.java:366)
                            	at io.sentry.SentryEvent$Deserializer.deserialize(SentryEvent.java:307)
                            	at io.sentry.JsonSerializer.deserialize(JsonSerializer.java:154)
                            	at io.sentry.OutboxSender.processEnvelope(OutboxSender.java:134)
                            	at io.sentry.OutboxSender.processFile(OutboxSender.java:74)
                            	at io.sentry.OutboxSender.processEnvelopeFile(OutboxSender.java:112)
                            	at io.sentry.android.core.EnvelopeFileObserver.onEvent(EnvelopeFileObserver.java:64)
                            	at android.os.FileObserver$ObserverThread.onEvent(FileObserver.java:166)
                            	at android.os.FileObserver$ObserverThread.observe(Native Method)
                            	at android.os.FileObserver$ObserverThread.run(FileObserver.java:116)
```

Which is obviously wrong. 

I am on SentryCapcitor version:

```
    "@sentry/capacitor": "0.12.2",
```

**Comment by lucas-zimerman** [comment]
Hi and thank you for opening the PR!.

would you mind sharing the minimal steps that you are using to capture this exception?

**Comment by mlostekk** [comment]
lets continue the discussion in here https://github.com/getsentry/sentry-capacitor/issues/450 as i think the issues are related
