### ISSUE TITLE
Support Web

### ISSUE THREAD

**Issue by muuvmuuv** [getsentry/sentry-capacitor#63]
### Environment

How do you use Sentry?
Sentry SaaS

Which SDK and version?
@sentry/capacitor@0.3.0

### Steps to Reproduce

1. Followed the README
2. Started my Ionic app in the browser

### Expected Result

Fallback to JS SDK (Angular is my case)?

### Actual Result

```
instrument.js:109 Unhandled Promise rejection: Native Client is not available, can't start on native. ; Zone: <root> ; Task: null ; Value: SentryError: Native Client is not available, can't start on native.
    at new SentryError (error.js:8)
    at Object.35046 (wrapper.js:291)
    at __webpack_require__ (bootstrap:19)
    at Object.51297 (sdkinfo.js:6)
    at __webpack_require__ (bootstrap:19)
    at Object.56889 (index.js:5)
    at __webpack_require__ (bootstrap:19)
    at Object.39167 (sdk.js:7)
    at __webpack_require__ (bootstrap:19)
    at Object.79555 (index.js:29) SentryError: Native Client is not available, can't start on native.
    at new SentryError (http://localhost:8100/vendor.js:90528:28)
    at Object.35046 (http://localhost:8100/vendor.js:85627:25)
    at __webpack_require__ (http://localhost:8100/runtime.js:23:42)
    at Object.51297 (http://localhost:8100/vendor.js:85023:17)
    at __webpack_require__ (http://localhost:8100/runtime.js:23:42)
    at Object.56889 (http://localhost:8100/vendor.js:85006:17)
    at __webpack_require__ (http://localhost:8100/runtime.js:23:42)
    at Object.39167 (http://localhost:8100/vendor.js:85210:22)
    at __webpack_require__ (http://localhost:8100/runtime.js:23:42)
    at Object.79555 (http://localhost:8100/vendor.js:84950:13)
(anonymous) @ instrument.js:109
api.onUnhandledError @ zone.js:1063
handleUnhandledRejection @ zone.js:1088
api.microtaskDrainDone @ zone.js:1082
drainMicroTaskQueue @ zone.js:589
Promise.then (async)
scheduleMicroTask @ zone.js:565
scheduleTask @ zone.js:396
scheduleTask @ zone.js:221
scheduleMicroTask @ zone.js:241
scheduleResolveOrReject @ zone.js:1266
then @ zone.js:1410
setDriver @ localforage.js:2734
LocalForage @ localforage.js:2523
4.3 @ localforage.js:2796
s @ localforage.js:7
e @ localforage.js:7
(anonymous) @ localforage.js:7
(anonymous) @ localforage.js:7
92430 @ localforage.js:7
__webpack_require__ @ bootstrap:19
21014 @ vendor.js:88971
__webpack_require__ @ bootstrap:19
39462 @ vendor.js:88934
__webpack_require__ @ bootstrap:19
39167 @ sdk.js:6
__webpack_require__ @ bootstrap:19
79555 @ index.js:29
__webpack_require__ @ bootstrap:19
14431 @ environment.ts:21
__webpack_require__ @ bootstrap:19
__webpack_exec__ @ main.js:4245
(anonymous) @ main.js:4246
__webpack_require__.O @ chunk loaded:25
(anonymous) @ main.js:4247
webpackJsonpCallback @ jsonp chunk loading:72
(anonymous) @ main.js:1
error.js:8 Uncaught SentryError: Native Client is not available, can't start on native.
    at new SentryError (error.js:8)
    at Object.35046 (wrapper.js:291)
    at __webpack_require__ (bootstrap:19)
    at Object.51297 (sdkinfo.js:6)
    at __webpack_require__ (bootstrap:19)
    at Object.56889 (index.js:5)
    at __webpack_require__ (bootstrap:19)
    at Object.39167 (sdk.js:7)
    at __webpack_require__ (bootstrap:19)
    at Object.79555 (index.js:29)
SentryError @ error.js:8
35046 @ wrapper.js:291
__webpack_require__ @ bootstrap:19
51297 @ sdkinfo.js:6
__webpack_require__ @ bootstrap:19
56889 @ index.js:5
__webpack_require__ @ bootstrap:19
39167 @ sdk.js:7
__webpack_require__ @ bootstrap:19
79555 @ index.js:29
__webpack_require__ @ bootstrap:19
14431 @ environment.ts:21
__webpack_require__ @ bootstrap:19
__webpack_exec__ @ main.js:4245
(anonymous) @ main.js:4246
__webpack_require__.O @ chunk loaded:25
(anonymous) @ main.js:4247
webpackJsonpCallback @ jsonp chunk loading:72
(anonymous) @ main.js:1
zone.js:372 Uncaught (in promise) SentryError: Native Client is not available, can't start on native.
    at new SentryError (error.js:8)
    at Object.35046 (wrapper.js:291)
    at __webpack_require__ (bootstrap:19)
    at Object.51297 (sdkinfo.js:6)
    at __webpack_require__ (bootstrap:19)
    at Object.56889 (index.js:5)
    at __webpack_require__ (bootstrap:19)
    at Object.39167 (sdk.js:7)
    at __webpack_require__ (bootstrap:19)
    at Object.79555 (index.js:29)
```

**Comment by jennmueng** [comment]
@muuvmuuv This is due to us not officially supporting Capacitor on web yet with this SDK. You can get around it for now by something like

```js
Sentry.init({
  enableNative: Capacitor.getPlatform() !== "web"
})
```

**Comment by muuvmuuv** [comment]
Oh okay, thanks! Will use it for now. 

Wouldn't it make sense to use sentry react/angular/vue SDK as a web fallback? Since it is described as a requirement to include the angular init script in the capacitor init.

**Comment by davidemerritt** [comment]
+1 on this functionality, takes away some of the value to have to implement a web version when the capacitor implementation is already there.

**Comment by jennmueng** [comment]
@davidemerritt @muuvmuuv The SDK is already the web SDK but it just runs a native bridge + a native SDK (Sentry Cocoa, Android etc). Passing `enableNative: false` just disables the native bridge. What this is waiting on is just a PR to check that the platform is web, disable it, and then extensively test everything so we can officially guarantee that it is supported. In theory using the workaround I just mentioned it should already all work.

**Comment by davidemerritt** [comment]
Thanks - seems to be working from what I see.

**Comment by dodomui** [comment]
I'm still facing this issue, does it really fix?
It's working previsouly.
"@sentry/angular": "^7.3.1",
"@sentry/capacitor": "^0.6.1",
